/**
 * Kontenplan SKR04 (Auszug der wichtigsten Konten)
 */
export default {
    // Bestandskonten (Klasse 0-3)
    '0000': 'Eröffnungsbilanz',
    '0100': 'Immaterielle Vermögensgegenstände',
    '0400': 'Grundstücke ohne Bauten',
    '0500': 'Bauten auf eigenen Grundstücken',
    '0650': 'Technische Anlagen und Maschinen',
    '0700': 'Andere Anlagen, Betriebs- und Geschäftsausstattung',
    '1200': 'Bank',
    '1210': 'Kasse',
    '1300': 'Forderungen aus Lieferungen und Leistungen',
    '1576': 'Vorsteuer 19%',
    '1577': 'Vorsteuer 7%',
    '1590': 'Umsatzsteuer-Vorauszahlungen',
    '1600': 'Forderungen gegen Gesellschafter',
    '1776': 'Umsatzsteuer 19%',
    '1777': 'Umsatzsteuer 7%',
    '1790': 'Umsatzsteuer-Vorauszahlungen',
    '2000': 'Gezeichnetes Kapital',
    '2100': 'Kapitalrücklage',
    '2970': 'Gewinnvortrag vor Verwendung',
    '2978': 'Verlustvortrag vor Verwendung',
    '3100': 'Darlehen',
    '3150': 'Verbindlichkeiten gegenüber Kreditinstituten',
    '3200': 'Verbindlichkeiten aus Lieferungen und Leistungen',
    '3300': 'Verbindlichkeiten gegenüber Gesellschaftern',
    '3820': 'Umsatzsteuer-Vorauszahlungen',

    // Erlöskonten (Klasse 4)
    '4000': 'Umsatzerlöse',
    '4120': 'Provisionserlöse',
    '4130': 'Zinsertrag',
    '4180': 'Erträge aus Vermietung und Verpachtung',
    '4190': 'Erträge aus Zuschüssen und Zulagen',
    '4200': 'Erlösschmälerung',
    '4400': 'Erlöse aus Lieferungen und Leistungen',
    '4830': 'Sonstige betriebliche Erträge',
    '4840': 'Erträge aus Währungsumrechnung',
    '4855': 'Erträge aus Anlagenabgang',

    // Aufwandskonten (Klasse 5-7)
    '5000': 'Wareneinsatz',
    '5300': 'Bezogene Leistungen',
    '5400': 'Roh-, Hilfs- und Betriebsstoffe',
    '6000': 'Löhne und Gehälter',
    '6010': 'Gesetzliche soziale Aufwendungen',
    '6020': 'Sonstige Personalkosten',
    '6200': 'Abschreibungen auf Sachanlagen',
    '6210': 'Abschreibungen auf Büroausstattung',
    '6220': 'Abschreibungen auf immaterielle Vermögensgegenstände',
    '6240': 'Leasingkosten',
    '6300': 'Betriebskosten',
    '6310': 'Miete',
    '6320': 'Nebenkosten',
    '6400': 'Versicherungen',
    '6500': 'IT-Kosten',
    '6600': 'Werbekosten',
    '6650': 'Reisekosten',
    '6670': 'Bewirtungskosten',
    '6800': 'Sonstige betriebliche Aufwendungen',
    '6805': 'Telefon und Internet',
    '6810': 'Porto',
    '6815': 'Bürobedarf',
    '6830': 'Fortbildungskosten',
    '7300': 'Zinsaufwendungen für Bankdarlehen',
    '7310': 'Zinsaufwendungen für Gesellschafterdarlehen',
    '7600': 'Körperschaftsteuer',
    '7610': 'Gewerbesteuer',
    '7620': 'Solidaritätszuschlag',
    '7630': 'Sonstige Steuern',

    // Abschlusskonten (Klasse 8-9)
    '8000': 'Eröffnungsbilanzkonto',
    '8400': 'Abschlussbilanzkonto',
    '8999': 'Gewinn- und Verlustkonto',
};